### ISSUE TITLE
clr_dumplsass 

### ISSUE THREAD

**Issue by ttsite** [uknowsec/SharpSQLTools#1]
clr_dumplsass  Function is to do what to use, there is no detailed use of the process. Thank you!

**Comment by Adminisme** [comment]
> clr_dumplsass Function is to do what to use, there is no detailed use of the process. Thank you!
此功能作者应该是引用了这个项目https://github.com/GhostPack/SharpDump，但是此功能存在一些问题，由于没有看CLR程序集的具体代码无法分析，具体表现为dump出的文件无法被mimikatz正常读取。

**Comment by uknowsec** [comment]
> > clr_dumplsass Function is to do what to use, there is no detailed use of the process. Thank you!
> > 此功能作者应该是引用了这个项目[https://github.com/GhostPack/SharpDump，但是此功能存在一些问题，由于没有看CLR程序集的具体代码无法分析，具体表现为dump出的文件无法被mimikatz正常读取。](https://github.com/GhostPack/SharpDump%EF%BC%8C%E4%BD%86%E6%98%AF%E6%AD%A4%E5%8A%9F%E8%83%BD%E5%AD%98%E5%9C%A8%E4%B8%80%E4%BA%9B%E9%97%AE%E9%A2%98%EF%BC%8C%E7%94%B1%E4%BA%8E%E6%B2%A1%E6%9C%89%E7%9C%8BCLR%E7%A8%8B%E5%BA%8F%E9%9B%86%E7%9A%84%E5%85%B7%E4%BD%93%E4%BB%A3%E7%A0%81%E6%97%A0%E6%B3%95%E5%88%86%E6%9E%90%EF%BC%8C%E5%85%B7%E4%BD%93%E8%A1%A8%E7%8E%B0%E4%B8%BAdump%E5%87%BA%E7%9A%84%E6%96%87%E4%BB%B6%E6%97%A0%E6%B3%95%E8%A2%ABmimikatz%E6%AD%A3%E5%B8%B8%E8%AF%BB%E5%8F%96%E3%80%82)

clr_dumplsass 功能就是引用的sharpdump，这个功能是可以用的，dump后将debug.bin文件修改为debug.gz然后进行解压缩，然后用相应版本的mimikatz进行读取就行了。
![](https://ae01.alicdn.com/kf/Ufbfd48297c91410ca30c198e81abeaa70.jpg)
