### ISSUE TITLE
Some specific passwords cannot be connected with tools

### ISSUE THREAD

**Issue by ttsite** [uknowsec/SharpSQLTools#11]
Some specific passwords cannot be connected with tools
for example  Aa$%^*%@

**Comment by uknowsec** [comment]
^在cmd中是转义字符
`d:\>echo ^*
*

d:\>echo ^
More?
More?

d:\>echo ^^
^`
比如：Aa$%^*%@ 你可以输入为Aa$%^^*%@
`SharpSQLTools.exe 192.168.247.139 sa Aa$%^^*%@ master xp_cmdshell whoami
[*] Database connection is successful! 2021/6/22 15:36:47

nt authority\system`

**Comment by ttsite** [comment]
thanks
