### ISSUE TITLE
Can I change it to Gui version?

### ISSUE THREAD

**Issue by ttsite** [uknowsec/SharpSQLTools#13]
I don't know if it can be changed to Gui version, so it's more convenient to operate. Thank you!!

**Comment by uknowsec** [comment]
https://github.com/RowTeam/SharpSQLTools/releases/download/untagged-0a25c864e3a1af7a948d/SharpSQLToolsGUI.zip

**Comment by uknowsec** [comment]
> I don't know if it can be changed to Gui version, so it's more convenient to operate. Thank you!!

https://github.com/RowTeam/SharpSQLTools/releases/download/untagged-0a25c864e3a1af7a948d/SharpSQLToolsGUI.zip

**Comment by ttsite** [comment]
Thank you for your reply. It seems that the function you sent is not very comprehensive. It's not as comprehensive as the function on your website!

**Comment by uknowsec** [comment]
> Thank you for your reply. It seems that the function you sent is not very comprehensive. It's not as comprehensive as the function on your website!

后面大概率不会去给gui版本加功能了，cli已经满足了日常使用需求了
