### ISSUE TITLE
360杀毒下的问题

### ISSUE THREAD

**Issue by whosisgood88** [uknowsec/SharpSQLTools#14]
mssql存在360杀毒下，执行命令会告警，包含clr在内的三种模式，但是通过clr_scloader的apc注入可以上线cs，但是目标主机如果不出网，去做端口抓发在弹出来有点麻烦，师傅有方便点的绕过吗？

**Comment by uknowsec** [comment]
360监控了cmd.exe，clr和其他方法执行命令都是调用cmd.exe。

**Comment by uknowsec** [comment]
> mssql存在360杀毒下，执行命令会告警，包含clr在内的三种模式，但是通过clr_scloader的apc注入可以上线cs，但是目标主机如果不出网，去做端口抓发在弹出来有点麻烦，师傅有方便点的绕过吗？

360监控了cmd.exe，clr和其他方法执行命令都是调用cmd.exe。
