### ISSUE TITLE
空密码怎么连接？

### ISSUE THREAD

**Issue by shadow1ng** [uknowsec/SharpSQLTools#16]
试了下面几个不行
SharpSQLTools.exe 1.1.1.1    master enable_clr
SharpSQLTools.exe 1.1.1.1 "" master enable_clr
SharpSQLTools.exe 1.1.1.1 '' master enable_clr

**Comment by okm404** [comment]
+1求问

**Comment by uknowsec** [comment]
> master enable_clr

![image](https://user-images.githubusercontent.com/20904482/139655800-50e8154b-c5c1-4ae6-9c46-ff76ab39710e.png)
emmm 你不输入用户名的么？

**Comment by uknowsec** [comment]
> > master enable_clr
> 
> ![image](https://user-images.githubusercontent.com/20904482/139655701-982925fe-6498-4e75-a124-74707a02dbb8.png)
> 
> emmm 你不输入用户名的么？
