### ISSUE TITLE
CLR

### ISSUE THREAD

**Issue by Adminisme** [uknowsec/SharpSQLTools#2]
能否提供CLR程序集的代码，方便增加新的功能。

**Comment by uknowsec** [comment]
> 能否提供CLR程序集的代码，方便增加新的功能。

有兴趣可以自行反编译获取程序集代码

https://github.com/uknowsec/SharpSQLTools/blob/master/SharpSQLTools/Setting.cs#L66

**Comment by Adminisme** [comment]
好的，谢谢师傅。👍 👍 👍 
在本地测试了一下师傅的工具，可以成功dump出文件，但mimikazt读取该文件依旧没有成功提取到密码，但直接使用SharpDump运行后dump出的文件，mimikazt却可以从该文件成功提取到密码！
刚才已经通过unhex获取到该dll，反编译看了一下师傅的代码，感觉问题应该出现在class dumplsass中的Minidump()的逻辑，但没有具体测试，主要想看一下师傅能否方便直接提供CLR程序集的代码直接本地调试一下，看一下是具体是什么问题。
![image](https://user-images.githubusercontent.com/26275596/105635818-0533ef00-5ea0-11eb-8b34-aa4d039b7a52.png)
![image](https://user-images.githubusercontent.com/26275596/105636105-98215900-5ea1-11eb-88a4-efafe5c3dee4.png)

**Comment by uknowsec** [comment]
> 好的，谢谢师傅。👍 👍 👍
> 在本地测试了一下师傅的工具，可以成功dump出文件，但mimikazt读取该文件依旧没有成功提取到密码，但直接使用SharpDump运行后dump出的文件，mimikazt却可以从该文件成功提取到密码！
> 刚才已经通过unhex获取到该dll，反编译看了一下师傅的代码，感觉问题应该出现在class dumplsass中的Minidump()的逻辑，但没有具体测试，主要想看一下师傅能否方便直接提供CLR程序集的代码直接本地调试一下，看一下是具体是什么问题。
> ![image](https://user-images.githubusercontent.com/26275596/105635818-0533ef00-5ea0-11eb-8b34-aa4d039b7a52.png)
> ![image](https://user-images.githubusercontent.com/26275596/105636105-98215900-5ea1-11eb-88a4-efafe5c3dee4.png)

https://github.com/uknowsec/SharpSQLTools/issues/1#issuecomment-766366449
我昨晚测试完全没问题呀。
