### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by 0ps** [uknowsec/SharpSQLTools#22]
C:\Users\Administrator\Desktop\exp>SharpSQLTools.exe 192.168.1.1 sa kkk?kkk(kkkk xp_cmdshell master whoami
[!] Error log:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by uknowsec** [comment]
参考 https://github.com/uknowsec/SharpSQLTools/issues/11
