### ISSUE TITLE
Can I customize CLR_ Directory of dumplsass export file

### ISSUE THREAD

**Issue by ttsite** [uknowsec/SharpSQLTools#8]
Most of the time, the temp directory under Windows does not have permission to write to the file. Can you write the CLR_ Dumplsass out of the file can customize the directory. In your source code, I did not find a place to change the directory. Thank you!

**Comment by JCCD** [comment]
+1

**Comment by ttsite** [comment]
+1

**Comment by uknowsec** [comment]
最新版支持指定dump目录，请下载最新版测试。
