### ISSUE TITLE
'System' 附近有语法错误

### ISSUE THREAD

**Issue by TryA9ain** [uknowsec/SharpSQLTools#9]
师傅，system 权限，上传时提示 'System' 附近有语法错误
`SharpSQLTools.exe 19x.1xx.1xx.55 sa sjs@sjs123 upload C:\Users\Administrator\Desktop\svchost.exe c:\windows\temp\svchost.exe`

![image](https://user-images.githubusercontent.com/51145610/117393300-6733d400-af26-11eb-9cfc-a0d0f4096af6.png)

**Comment by uknowsec** [comment]
我这边在2008和2012两个版本不同权限下都测试了，并没有发现这个问题。有需要可以下载最新版测试一下

**Comment by uknowsec** [comment]
> 师傅，system 权限，上传时提示 'System' 附近有语法错误
> `SharpSQLTools.exe 19x.1xx.1xx.55 sa sjs@sjs123 upload C:\Users\Administrator\Desktop\svchost.exe c:\windows\temp\svchost.exe`
> 
> ![image](https://user-images.githubusercontent.com/51145610/117393300-6733d400-af26-11eb-9cfc-a0d0f4096af6.png)

更新了一下上传时读取本地文件和分割的方法，可以尝试最新版是否还报错

**Comment by uknowsec** [comment]
> > 师傅，system 权限，上传时提示 'System' 附近有语法错误
> > `SharpSQLTools.exe 19x.1xx.1xx.55 sa sjs@sjs123 upload C:\Users\Administrator\Desktop\svchost.exe c:\windows\temp\svchost.exe`
> > ![image](https://user-images.githubusercontent.com/51145610/117393300-6733d400-af26-11eb-9cfc-a0d0f4096af6.png)
> 
> 更新了一下上传时读取本地文件和分割的方法，可以尝试最新版是否还报错

有其他师傅出现同样的错误，最新版本的已经测试通过，可以下载最新版本进行使用。
